services:
  nocodb:
    image: nocodb/nocodb
    environment:
      - SERVICE_FQDN_NOCODB_8080
    volumes:
      - 'nocodb-data:/usr/app/data/'
    healthcheck:
      test:
        - CMD
        - wget
        - '-q'
        - '--spider'
        - 'http://127.0.0.1:8080/api/v1/health'
      interval: 5s
      timeout: 20s
      retries: 10
  express:
    build:
      context: /opt/scripts/app
    container_name: express-app
    volumes:
      - 'nocodb-data:/usr/app/data/'
      - 'express-nocodb_backups:/opt/nocodb_backups'
    ports:
      - '3005:3005'
    environment:
      - NODE_ENV=production
    restart: unless-stopped
volumes:
  nocodb-data: null
  express-nocodb_backups: null

