services:
  filebrowser:
    image: 'filebrowser/filebrowser:latest'
    environment:
      - SERVICE_FQDN_FILEBROWSER_80
      - PUID=1000
      - PGID=1000
    volumes:
      - "/var/lib/docker/volumes/t0oog4kssskwocwk0o0okwkg_nocodb-data/_data:/home/nocodb:ro"
      - "/var/lib/docker/volumes/t0oog4kssskwocwk0o0okwkg_express-nocodb-backups/_data:/home/express:ro"
      - "/:/home/server"
      - "./database.db:/database.db"
      - "./filebrowser.json:/.filebrowser.json"
      # -
      #   type: bind
      #   source: ./srv
      #   target: /srv
      #   isDirectory: true
      # -
      #   type: bind
      #   source: ./database.db
      #   target: /database.db
      #   isDirectory: false
      #   content: ''
      # -
      #   type: bind
      #   source: ./filebrowser.json
      #   target: /.filebrowser.json
      #   read_only: true
      #   content: "{\n  \"address\": \"0.0.0.0\",\n  \"port\": 80\n}"
    healthcheck:
      test:
        - CMD
        - curl
        - '-f'
        - 'http://127.0.0.1:80'
      interval: 2s
      timeout: 10s
      retries: 15

