services:
  portainer:
    image: portainer/portainer-ce
    container_name: portainer
    restart: always
    ports:
      - "9000:9000"
    networks:
      - npm_network
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data

  npm:
    image: jc21/nginx-proxy-manager:latest
    container_name: npm
    restart: always
    ports:
      - "80:80"
      - "81:81"
      - "443:443"
    networks:
      - npm_network
    volumes:
      - npm_data:/data
      - npm_letsencrypt:/etc/letsencrypt

networks:
  npm_network:
    name: npm_network
    external: true
    driver: bridge
    enable_ipv6: true
    ipam:
      driver: default
      config:
        - subnet: "2a01:4f8:c17:7041::/64"  # Replace with your real IPv6 subnet

volumes:
  portainer_data:
  npm_data:
  npm_letsencrypt:


